services:
  db:
    image: postgres:15
    container_name: postgres_mentia
    restart: always
    environment:
      POSTGRES_DB: MentIA
      POSTGRES_USER: mentia
      POSTGRES_PASSWORD: MentIA2025
    ports:
      - "6000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
